# This does Travis CI builds on Linux and OS X, and on a tag build,
# also produces an OS X package.
os:
  - linux
  - osx

cache:
  - apt

language: cpp

# Use the Ubuntu 14.04 build environment for Linux.
sudo: required
dist: trusty

# Use whatever Travis likes + DEPLOYMENT_TARGET=10.12
osx_image: xcode9.2

# Linux dependencies
addons:
  apt:
    packages:
    # For build.
    - protobuf-compiler
    - libprotobuf-dev
    - libutempter-dev
    # Test suite needs these.
    - tmux
    - perl

before_install:
  # Get full repo for `git describe`
  - git fetch --tags --unshallow
  # OS X dependencies.  The package_deps step takes 15 minutes or so
  # and is fairly quiet, so wrap it in travis_wait to keep it from
  # being killed.
  - |
    if test osx = "${TRAVIS_OS_NAME}"; then
      macosx/brew-deps.sh install && macosx/brew-deps.sh deps
    fi

# Use before_script to report the build configuration.
before_script:
  # Describe this system.
  - id
  - env
  - git describe --long

# 'make distcheck', and OS X package build on tag builds.
script:
  - |
    if test osx = "${TRAVIS_OS_NAME}"; then
      sysctl hw.ncpu
    fi
  - ./autogen.sh
  - ./configure --enable-compile-warnings=error --enable-examples
  - make distcheck VERBOSE=1 V=1

# Deploy the OS X package and its build report to a GitHub release.
deploy:
  provider: releases
  api_key:
    secure: "QCaIoFG1gTS/b0kJ4j996NY8nyt9UvnREhzc9op2ZYNZd0T9K1CNt8YqeSlUvDCls4e1tiQf7uipAdaEJHIX4jaecuon71dTUOGVyzLyvQmnu3Mz00+KNTNFeIRkAtk/5Zy0t0QzCWFdoZYlneK99V9AL7EUPBXlmDOWIggZilkCVP45f2OdsO226a1yPmtXuOjCR01jlpbe9MTkbIzZDX50LP/0xWwXnaA4QqKnKZSG17xqgHJujSzkC5cSW2tcRIDQj+7eX3G6mOSD2L4R7cdpIMj4nIFOjxnNpyvqj0pEhix+nQGErlbFDerjr4azOTFZHf9kj1BVUauLMQwWIafgYifIL+mm/YFAnaEmKi8pkCWisMEJ8AgrXs+6G4cbSfKT0Naz4PD40CheatCvgpxIaPkUd3MxmsTiZYJqTum44OSwP5aw7TWdMhPxQ5SmioZjZ7R+YuPa1sESiIVLv4gySc9Gj0Y2Zz6v9dfFHS1mAePL18EFclRjoWwAkycIIKTctv6fPGa7FiGMXpbQMqBFQEQimcq3ELIoO2D1zCgUIXWtMPXsK8HgNe5MDPDX1MtBxlYZQ2Imo8q87JzKB+LKGdEIketoPKMxnNpPXc1ol/TU+GRD/kddpDkdQ/ef0ISsPEeGWT0FEmk7Cr9l9gK9N+0crnSfB88O+4BtE3c="
  # Save build artifacts.
  skip_cleanup: true
  # Using a shell variable in deploy.file is undocumented but seems to work.
  file:
#    - macosx/${TRAVIS_TAG}.pkg
#    - macosx/${TRAVIS_TAG}-osx-build-report.tbz
    - scripts/mosh
      src/frontend/mosh-client
      src/frontend/mosh-server
  on:
    repo: mobile-shell/mosh
    tags: true

# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#mosh"
#     skip_join: true
